FROM envoyproxy/envoy:v1.13.0

LABEL maintainer="dimitrij.drus@innoq.com"

RUN apt-get update && apt-get -q install -y curl

CMD /usr/local/bin/envoy -c /etc/front-envoy.yaml --service-cluster front-proxy
